spring.application.name=RiskFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/riskflow
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.generate-ddl=true
spring.flyway.validate-migration-naming=true

